### ISSUE TITLE
Compressed syntax?

### ISSUE THREAD

**Issue by nedrichards** [hughsie/oars#17]
In [feedback for a PR Vasily Galkin noted](https://gitlab.gnome.org/GNOME/meld/merge_requests/11#note_232403)

> As far as I understand the version "oars-1.1" standardize the list of expected ids. Is there some syntax to indicate that all ids included in standard except explicitly specified are set to none?

> Such syntax would make such sections much more readable, since even  chats/games/shopping-apps/etc would only set relevant tags without listing all that .

> For apps like meld it would be extremely more readable: having a single line indication that "all content attributes for oars version X.Y were checked" (so all of them are none) - for me it looks more readable than explicitly listing  them.

This seemed like interesting feedback, especially as the range of properties is expected to grow.

**Comment by hughsie** [comment]
I agree with this. Initially I was for showing all the categories to signify "I've checked this" but we know what categories a given specification version has, so we can infer none from the version and the ratings type. I can fix the builder to not emit the `none` lines if that would be helpful.

**Comment by nedrichards** [comment]
lgtm - feel free to close when deployed.
