### ISSUE TITLE
Be less game specific

### ISSUE THREAD

**Issue by nedrichards** [hughsie/oars#2]
Games are a really important use case for OARS, however it'd be awesome if we could cover more categories of apps. Even if it's just to make creators of those apps feel more 'welcome' in using the interface. This is feedback we've heard a lot on Flathub as we're encouraging app developers to add OARS metadata to their appdata.

**Comment by julianrichen** [comment]
A specific example would be "In-Game Purchases". Applications like [LBRY](https://github.com/flathub/flathub/pull/175) have the ability to buy/donate. "In-App Purchases" would be more generic and I believe many mobile games/app use this terminology already.

Same thing with many of the options under Social. Simply renaming "Players" to "Users" would convey the same message and be more generic.

**Comment by hughsie** [comment]
I've added a `money-purchasing=mild` which says: Users are encouraged to donate to the project

I've also renamed players to users in a couple of places. Hopefully something more interesting to show soon. :)

**Comment by hughsie** [comment]
Take a look at https://hughsie.github.io/oars/ for a sneak peak.
