### ISSUE TITLE
Clarify `social-info` `mild`

### ISSUE THREAD

**Issue by cassidyjames** [hughsie/oars#22]
Similar to (but more specific than) #15. Several apps submitted to AppCenter use online APIs. The applications themselves may not collect any data, but the fact that they ping an online service at all (potentially revealing IP address and any other data sent/received) has privacy implications.

For AppCenter, we've interpreted this case as at social-info: mild or above (depending on data sent). However, it's not clear that using an online API at all would require this rating from the generator. Perhaps this could be clarified in the generator text?

**Comment by hughsie** [comment]
I think `social-info: mild` is perfect for this. Did you have any text in mind on how to clarify this? I'm useless at words :(
