### ISSUE TITLE
Expose the level in the dropdowns

### ISSUE THREAD

**Issue by cassidyjames** [hughsie/oars#25]
It would make it easier to refer to specific items in the generator if each item in dropdowns included the level; i.e. instead of just:

>Using an online API, e.g. a user-counter

…it could read:

>Mild: Using an online API, e.g. a user counter

This makes the relationship between the dropdowns more clear and helps the make the generated XML less surprising to developers. It also makes it easier for elementary documentation as we can refer to the dropdowns by their level instead of the descriptions themselves (which could be more liable to change).

**Comment by hughsie** [comment]
Yup, I'd agree with that.
