### ISSUE TITLE
Generator: steer “content-rich” apps through the content questions

### ISSUE THREAD

**Issue by wjt** [hughsie/oars#30]
Currently, the generator offers four classes of apps:

 * Game with networking
 * Game that does not use any kind of network access
 * Application that can connect to the Internet
 * Application that does not use the Internet

If you choose “Application […]” rather than “Game […]”, you don't get any questions about content. But there are apps other than games that contain potentially-objectionable content:

* Endless ships encyclopedias and other “knowledge” apps that contain lots of built-in content. History apps, for example, may well contain references to the Crusades – the exemplar for `violence-worship` `mild`.
* Flathub has apps which distribute religious texts. I am not an expert, but I'm pretty sure there are references to historical slavery in the Bible.
* (I'm sure there are other examples.)

I think the wording on the generator should be changed to steer authors of apps like these through some (but perhaps not all) of the content questions.

(This was also raised here: https://github.com/flathub/flathub/issues/1081#issuecomment-519594124)

**Comment by hughsie** [comment]
I guess I agree about unhiding the content for apps. Can you wrangle a patch up? Thanks.
