### ISSUE TITLE
Some concerns regarding the cultural sensitivity questions

### ISSUE THREAD

**Issue by o-alquimista** [hughsie/oars#35]
I had previously opened an [issue](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/993) on the GNOME Software bug tracker sharing some concerns I had about two of the cultural sensitivity questions. When I wrote it, I assumed it was a GNOME Software thing. Someone then pointed that OARS is responsible for the rating system.

Below is everything I wrote there, unchanged. I'd like to know your opinion on this matter.

______________________________________________

The age rating system contains *"Without reference to homosexuality"* and *"Without reference to adultery"* as justification for certain ratings.

![Captura_de_tela_de_2020-05-17_16-46-30](https://user-images.githubusercontent.com/25424263/82160939-20f5e880-986f-11ea-8e16-721e1ba050fb.png)

I propose removing *"Without reference to homosexuality"* for the following reasons:

* Homosexuality is a sexual orientation just like heterosexuality. Since there is no equivalent justification for heterosexuality or any other sexual orientation in the age rating system, this may be considered homophobia.

* There is already a line saying (translating from Portuguese, may be a little off) *"No reference to or any representation of sexual nature"*. It already covers "any sexual content", so mentioning homosexuality there is not only homophobic, but also redundant.

I propose removing *"Without reference to adultery"* for the following reason:

* Adultery historically comes from religious grounds. It may be a crime in some places, but mostly it falls down to cultural, religious or personal beliefs. For a software meant to be used all around the world, it is best not to be partial in this matter.

* Either way, it is redundant. The line *"No reference to or any representation of sexual nature"* should cover it.

There are many other redundant justifications in there. It would be best to carefully review them all.

**Comment by hughsie** [comment]
> I propose removing "Without reference to homosexuality" 

NAK.

> Homosexuality is a sexual orientation just like heterosexuality

I agree. We don't all live in an equal world. In some countries homosexuality is 100% illegal, even punishable by death. To distribute software in these crazy countries we need to tag software like OARS does.

> so mentioning homosexuality there is not only homophobic

That's not homophobic.

> I propose removing "Without reference to adultery"

Also punishable by death in some countries. Supplying software with references to adultery, or in any way encouraging or making light of it is a crime in many countries.

> It would be best to carefully review them all.

We have reviewed them all. OARS is not designed for software just shipping in Western countries. The world is not as ideal as you and I would hope it could be.

**Comment by o-alquimista** [comment]
> I agree. We don't all live in an equal world. In some countries homosexuality is 100% illegal, even punishable by death. To distribute software in these crazy countries we need to tag software like OARS does.

> Also punishable by death in some countries. Supplying software with references to adultery, or in any way encouraging or making light of it is a crime in many countries.

Thank you for explaining these things. I was unaware that there were legal requirements.

I only brought this up because that line was seen as homophobic by some people around me. Maybe because of the way they are written?

May I suggest the addition of a label or warning for these "cultural sensitivity" questions to separate them from the other items? Or simply a note with them saying "Some of these items are of cultural sensitivity (...) there are legal reasons for their presence (...)" to avoid having this issue brought up again by someone else in the future. If adding a note is up to other software (such as GNOME Software, Flatpak, etc.), it could at least become a requirement to them. What do you think?

**Comment by hughsie** [comment]
> Some of these items are of cultural sensitivity

**Comment by hughsie** [comment]
I'd argue that a lot of those are culturally sensitive. E.g. desecration of a dead body == punishable by death. It all depends on your culture.

**Comment by OrionMoonclaw** [comment]
I'd actually argue that free software should be free (ha? get it?) from such biases and discrimination. Putting in these labels can reinforce and rationalize the bigotry behind them which is of course no good and is actually itself shocking in our western civilization. Protect kids, not bigots.

**Comment by hughsie** [comment]
> and is actually itself shocking in our western civilization

We don't all live in a western civilization.

**Comment by OrionMoonclaw** [comment]
> > and is actually itself shocking in our western civilization
> 
> We don't all live in a western civilization.

Does that make it any better though? Would you be fine with including labels such as "Contains women" or "Contains mentions of women names" (Yeah, in some places it is considered offensive to use them in public and they should be instead reffered to via their husband's name). This shouldn't be about making a system that is universally acceptable by all cultures, that will fail no matter how hard you try and is pointless. The goal should be to make a GOOD system.

**Comment by hughsie** [comment]
I've pushed https://github.com/hughsie/oars/commit/bbb10186cbecb49252610e5604ed025df8f4c8b7 -- I'm not being paid for maintain OARS and if a company is using the specification to distribute software to countries that require filtering then they can add the extra metadata themselves. It's just not my problem, sorry. I really don't want to work on this project any more.
