### ISSUE TITLE
Legal issues regarding discrimination of homosexuality

### ISSUE THREAD

**Issue by bitcynth** [hughsie/oars#39]
Hi,

While I acknowledge that you feel like it is reasonable to include `sex-homosexuality` due to it being outlawed in certain jurisdictions.

I believe it is also important to note that in your jurisdiction it is not only legal but also protected by the Equality Act 2010 (along with many other European countries with similar laws).

And while I am not a lawyer I believe this qualifies as harassment due to this having the effect of violating the dignity of people purely on the aspect of them being homosexual.

And aside from the legal aspects, this is despicable on moral grounds.

And you mention the following:

```
However, in other countries (for example, the EU), discrimination laws explicitly prohibit discrimination on the basis of gender or sexuality. So while LGBT tagging may be available in OARS data, consumers of that data must only apply it in countries where the law requires that.
```

This is not adequate, you are still providing tools and services to facilitate discrimination of people based on homosexuality.

And once again while I am not a lawyer, I believe this probably counts as illegal discrimination according to UK law.

**Comment by hughsie** [comment]
> I believe this qualifies as harassment

Just to clarify, are you insinuating that I am personally harassing you? If not, who exactly is harassing who?

> while I am not a lawyer

If you wish to pursue this legal route I suggest you do indeed consult a lawyer.

> this is despicable on moral grounds

Many things are despicable on moral grounds, but unfortunately what is moral and what is illegal are very different things.

> you are still providing tools and services to facilitate discrimination of people based on homosexuality

First of all, "_providing tools and services to facilitate discrimination_" is not actually a crime, although it's important to note that is **not** what we're doing with OARS. Second of all, I don't believe any discrimination of a person from a protected class has actually occurred. The other issue you quoted explained **why** we have the `sex-homosexuality` category; as without it we can't supply software to countries that have regulations not only promoting discrimination, but actually requiring it in law. It's the same reality unfortunately for ESRB and PEGI. In fact, PEGI is more invasive as it asks more questions about other LGBT protected classes compared to OARS.

> I believe this probably counts as illegal discrimination according to UK law.

I would be very sure to check with a lawyer before writing things like that.

**Comment by hughsie** [comment]
I've pushed https://github.com/hughsie/oars/commit/bbb10186cbecb49252610e5604ed025df8f4c8b7 -- I'm not being paid for maintain OARS and if a company is using the specification to distribute software to countries that require filtering then they can add the extra metadata themselves. It's just not my problem, sorry. I really don't want to work on this project any more.

**Comment by bitcynth** [comment]
I appreciate your change, and I understand that it is difficult and not very fun work, especially if no one pays you for it.

But I also think that trying to make a system to comply with all local laws in every place knowing there is this kind of oppression was never realistically going to work.
