### ISSUE TITLE
Add KDE Discover into Distributors Using OARS

### ISSUE THREAD

**Issue by AsciiWolf** [hughsie/oars#46]
KDE Discover supports OARS since 5.26: https://invent.kde.org/plasma/discover/-/merge_requests/357

**Comment by hughsie** [comment]
Can you do a pull request please?

**Comment by AsciiWolf** [comment]
I will add this to my TODO. I am sadly overwhelmed with other work at the moment.

**Comment by AsciiWolf** [comment]
I was able to allocate some time today: # :-)

**Comment by AsciiWolf** [comment]
I was able to allocate some time today: #47 :-)

Untested, but should hopefully work fine.
