### ISSUE TITLE
Add Endless OS to distributors?

### ISSUE THREAD

**Issue by cassidyjames** [hughsie/oars#50]
This is more of a question; does it make sense to add Endless OS—or more broadly, individual OSes—to the distributors section? We use OARS for built-in parental controls, but that might also apply to other GNOME distros these days as well.

My instinct is that it does make sense, since it's a feature of the OS, and it better reflects the reality that OARS is actually widely used by distros.

Alternatively, we could add "GNOME Parental Controls" as its own item but 🤷🏻 

If it does make sense to add individual OSes, I'd be happy to submit a PR with a handful of distros that I've confirmed ship the OARS-powered parental controls ootb.

**Comment by hughsie** [comment]
I guess initially it was a bit spotty what distros actually shipped good enough metadata -- now it's basically most of them. I'd be okay either with adding Endless, or removing the others and just saying _GNOME_.

**Comment by cassidyjames** [comment]
To me it is better to have more distributors listed than fewer, so people can better clock that it's widely-used. I'll propose a PR!

**Comment by hughsie** [comment]
Thanks!
